apiVersion: batch/v1
kind: CronJob
metadata:
  name: refresher
  namespace: 12inch-reviews
spec:
  schedule: "30 * * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: regcred
          containers:
            - name: 12inch-reviews
              image: gammons1/12inch.reviews:v4
              env:
                - name: ALBUM_STORE_PATH
                  value: .
                - name: SPOTIFY_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: 12inchreviews-secrets
                      key: spotifyClientId
                - name: SPOTIFY_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: 12inchreviews-secrets
                      key: spotifyClientSecret
                - name: AWS_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: 12inchreviews-secrets
                      key: awsAccessKeyId
                - name: AWS_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: 12inchreviews-secrets
                      key: awsSecretAccessKey
              command:
                - "bundle"
                - "exec"
                - "rake"
