apiVersion: v1
kind: Pod
metadata:
  name: 12inchpod
  namespace: 12inch-reviews
spec:
  volumes:
  - name: mypd
    persistentVolumeClaim:
      claimName: albumstore
  containers:
  - name: 12inch-reviews
    image: gammons1/12inch.reviews:latest
    volumeMounts:
    - name: mypd
      mountPath: "/tmp/albumStore"
    env:
      - name: SPOTIFY_CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: 12inchreviews-secrets
            key: spotifyClientId
      - name: SPOTIFY_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: 12inchreviews-secrets
            key: spotifyClientSecret
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: 12inchreviews-secrets
            key: awsAccessKeyId
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: 12inchreviews-secrets
            key: awsSecretAccessKey
    command:
      - "/bin/bash"
      - "-c"
      - "sleep 10000"
