apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: albumstore
  namespace: 12inch-reviews
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
