# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord'
gem 'aws-sdk-s3'
gem 'byebug'
gem 'dotenv'
gem 'fuzzy_match'
gem 'http'
gem 'nokogiri'
gem 'spotify-search', git: 'https://github.com/gammons/spotify-search.git', branch: 'main'
gem 'sqlite3'

# gem "rails"
