apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: refresher
  namespace: 12inch-reviews
spec:
  schedule: "30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
          - name: regcred
          containers:
          - name: 12inch-reviews
            image: gammons1/12inch.reviews:latest
            env:
              - name: SPOTIFY_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    name: 12inchreviews-secrets
                    key: spotifyClientId
              - name: SPOTIFY_CLIENT_SECRET
                valueFrom:
                  secretKeyRef:
                    name: 12inchreviews-secrets
                    key: spotifyClientSecret
            command:
            - "rake"
            - "test"
