require "aws-sdk-s3"

require_relative "retrieve"
require_relative "lib/db_setup"

AWS_CREDS = Aws::Credentials.new(ENV['AWS_ACCESS_KEY_ID'], ENV['AWS_SECRET_ACCESS_KEY'])

desc "Backfill all the albums"
task :backfill do
  Retriever.new.backfill
end

desc "Refresh for new albums"
task :refresh do
  Retriever.new.refresh
end

task :create_albums_json_files do
  Retriever.new.create_albums_json_files

  client = Aws::S3::Client.new(region: "us-east-2", credentials: AWS_CREDS)

  total_files = Dir.glob("albums*.json").length
  body = JSON.generate({files: total_files, timestamp: Time.now.to_i})
  client.put_object({bucket: "12inch.reviews", key: "metadata.json", acl: "public-read", body: body})

  Dir.glob("albums*.json").each do |filename|
    File.open(filename, "rb") do |file|
      client.put_object({bucket: "12inch.reviews", key: filename, acl: "public-read", body: file})
    end
  end

  `rm -rf albums*.json`
end

task :setup_db do
  DBSetup.new.create!
end

task :docker_build do
  `docker build -t gammons1/12inch.reviews:latest .`
  `docker push gammons1/12inch.reviews:latest`
end

task :test do
  puts "testing!"
  puts "SPOTIFY_CLIENT_ID = '#{ENV['SPOTIFY_CLIENT_ID']}'"
  puts "SPOTIFY_CLIENT_SECRET = '#{ENV['SPOTIFY_CLIENT_SECRET']}'"
end

task default: :refresh
